export enum Specialisation {
  GeneralPractitioner,
  Cardiology,
  Neurology,
  Orthopedics,
  Pediatrics,
  Gynecology ,
  Obstetrics,
  Dermatology,
  Radiology,
  Anesthesiology,
  EmergencyMedicine,
  InternalMedicine,
  Oncology,
  Psychiatry,
  Urology,
  Ophthalmology,
  Otolaryngology,
  Pulmonology,
  Endocrinology,
  Gastroenterology,
}
