export enum Specialisation {
  GeneralPractitioner= "General Practitioner",
  Cardiology= "Cardiology",
  Neurology= "Neurology",
  Orthopedics= "Orthopedics",
  Pediatrics="Pediatrics",
  Gynecology="Gynecology" ,
  Obstetrics="Obstetrics",
  Dermatology="Dermatology",
  Radiology="Radiology",
  Anesthesiology="Anesthesiology",
  EmergencyMedicine="Emergency Medicine",
  InternalMedicine="Internal Medicine",
  Oncology="Oncology",
  Psychiatry="Psychiatry",
  Urology="Urology",
  Ophthalmology="Ophthalmology",
  Otolaryngology="Otolaryngology",
  Pulmonology="Pulmonology",
  Endocrinology="Endocrinology",
  Gastroenterology="Gastroenterology",
}
